"""Abbreviation information about MLB teams
"""

abbreviations = {
    "Diamondbacks": "ARI",
    "Braves":       "ATL",
    "Orioles":      "BAL",
    "Red Sox":      "BOS",
    "Cubs":         "CHC",
    "Reds":         "CIN",
    "Indians":      "CLE",
    "Rockies":      "COL",
    "White Sox":    "CWS",
    "Tigers":       "DET",
    "Astros":       "HOU",
    "Royals":        "KC",
    "Angels":       "LAA",
    "Dodgers":      "LAD",
    "Marlins":      "MIA",
    "Brewers":      "MIL",
    "Twins":        "MIN",
    "Mets":         "NYM",
    "Yankees":      "NYY",
    "Athletics":    "OAK",
    "Phillies":     "PHI",
    "Pirates":      "PIT",
    "Padres":        "SD",
    "Mariners":     "SEA",
    "Giants":        "SF",
    "Cardinals":    "SLT",
    "Rays":          "TB",
    "Rangers":      "TEX",
    "Blue Jays":    "TOR",
    "Nationals":    "WSH"
}


abbreviations_full = {
    "Arizona Diamondbacks":  "ARI",
    "Atlanta Braves":        "ATL",
    "Baltimore Orioles":     "BAL",
    "Boston Red Sox":        "BOS",
    "Chicago Cubs":          "CHC",
    "Cincinnati Reds":       "CIN",
    "Cleveland Indians":     "CLE",
    "Colorado Rockies":      "COL",
    "Chicago White Sox":     "CWS",
    "Detroit Tigers":        "DET",
    "Houston Astros":        "HOU",
    "Kansas City Royals":     "KC",
    "Los Angeles Angels":    "LAA",
    "Los Angeles Dodgers":   "LAD",
    "Miami Marlins":         "MIA",
    "Milwaukee Brewers":     "MIL",
    "Minnesota Twins":       "MIN",
    "New York Mets":         "NYM",
    "New York Yankees":      "NYY",
    "Oakland Athletics":     "OAK",
    "Philadelphia Phillies": "PHI",
    "Pittsburgh Pirates":    "PIT",
    "San Diego Padres":       "SD",
    "Seattle Mariners":      "SEA",
    "San Francisco Giants":   "SF",
    "St. Louis Cardinals":   "SLT",
    "Tampa Bay Rays":         "TB",
    "Texas Rangers":         "TEX",
    "Toronto Blue Jays":     "TOR",
    "Washington Nationals":  "WSH"
}
