"""Abbreviation information about NHL teams
"""

abbreviations = {
    "Ducks":            "ANA",
    "Coyotes":          "ARI",
    "Bruins":           "BOS",
    "Sabres":           "BUF",
    "Flames":           "CGY",
    "Hurricanes":       "CAR",
    "Blackhawks":       "CHI",
    "Avalanche":        "COL",
    "Blue Jackets":     "CBJ",
    "Stars":            "DAL",
    "Red Wings":        "DET",
    "Oilers":           "EDM",
    "Panthers":         "FLA",
    "Kings":            "LAK",
    "Wild":             "MIN",
    "Canadiens":        "MTL",
    "Predators":        "NSH",
    "Devils":           "NJD",
    "Islanders":        "NYI",
    "Rangers":          "NYR",
    "Senators":         "OTT",
    "Flyers":           "PHI",
    "Penguins":         "PIT",
    "Sharks":           "SJS",
    "Blues":            "STL",
    "Lightning":        "TBL",
    "Maple Leafs":      "TOR",
    "Canucks":          "VAN",
    "Golden Knights":   "VGK",
    "Capitals":         "WSH",
    "Jets":             "WIN"
}

abbreviations_full = {
    "Anaheim Ducks":            "ANA",
    "Arizona Coyotes":          "ARI",
    "Boston Bruins":            "BOS",
    "Buffalo Sabres":           "BUF",
    "Calgary Flames":           "CGY",
    "Carolina Hurricanes":      "CAR",
    "Chicago Blackhawks":       "CHI",
    "Colorado Avalanche":       "COL",
    "Columbus Blue Jackets":    "CBJ",
    "Dallas Stars":             "DAL",
    "Detroit Red Wings":        "DET",
    "Edmonton Oilers":          "EDM",
    "Florida Panthers":         "FLA",
    "Los Angeles Kings":        "LAK",
    "Minnesota Wild":           "MIN",
    "Montreal Canadiens":       "MTL",
    "Nashville Predators":      "NSH",
    "New Jersey Devils":        "NJD",
    "New York Islanders":       "NYI",
    "New York Rangers":         "NYR",
    "Ottawa Senators":          "OTT",
    "Philadelphia Flyers":      "PHI",
    "Pittsburgh Penguins":      "PIT",
    "San Jose Sharks":          "SJS",
    "St. Louis Blues":          "STL",
    "Tampa Bay Lightning":      "TBL",
    "Toronto Maple Leafs":      "TOR",
    "Vancouver Canucks":        "VAN",
    "Vegas Golden Knights":     "VGK",
    "Washington Capitals":      "WSH",
    "Winnipeg Jets":            "WIN"
}
