abbreviations = {
    "Ducks":            "ANA",
    "Coyotes":          "ARI",
    "Bruins":           "BOS",
    "Sabres":           "BUF",
    "Flames":           "CGY",
    "Hurricanes":       "CAR",
    "Blackhawks":       "CHI",
    "Avalanche":        "COL",
    "Blue Jackets":     "CBJ",
    "Stars":            "DAL",
    "Red Wings":        "DET",
    "Oilers":           "EDM",
    "Panthers":         "FLA",
    "Kings":            "LAK",
    "Wild":             "MIN",
    "Canadiens":        "MTL",
    "Predators":        "NSH",
    "Devils":           "NJD",
    "Islanders":        "NYI",
    "Rangers":          "NYR",
    "Senators":         "OTT",
    "Flyers":           "PHI",
    "Penguins":         "PIT",
    "Sharks":           "SJS",
    "Blues":            "STL",
    "Lightning":        "TBL",
    "Maple Leafs":      "TOR",
    "Canucks":          "VAN",
    "Golden Knights":   "VGK",
    "Capitals":         "WSH",
    "Jets":             "WIN"
}
